export const ELEMENTS = {
  NAVBAR: 'NavBar',
  MOVIES: 'Movies',
  HOME: 'Home',
  SERIES: 'Series',
  CONTENT: 'Content',
  BACKGROUND: 'Background',
  WIDGETCARD: 'WidgetCard',
  WIDGET: 'Widget',
  DETAILS: 'Details',
  WRAPPER: 'Wrapper',
  ICON: 'Icon',
  BACK_BUTTON: 'BackButton',
  META_INFO: 'MetaInfo',
  WHATCH_NOW: 'WatchNow',
}
